import { ArrowRight, Brush, Frame, Lightbulb, PackageCheck, ShieldCheck, Sparkles } from 'lucide-react';
import { useLanguage } from '@/lib/i18n';

type Page = 'home' | 'services' | 'painting' | 'sculpture' | 'about' | 'contact';
type ServicesProps = { onNavigate: (page: Page) => void };

export default function Services({ onNavigate }: ServicesProps) {
  const { t } = useLanguage();
  const services = [
    [Brush, 'services.s1Title', 'services.s1Desc'], [Sparkles, 'services.s2Title', 'services.s2Desc'], [Lightbulb, 'services.s3Title', 'services.s3Desc'], [ShieldCheck, 'services.s4Title', 'services.s4Desc'], [Frame, 'services.s5Title', 'services.s5Desc'], [PackageCheck, 'services.s6Title', 'services.s6Desc'],
  ] as const;
  const steps = [['01', 'services.step1Title', 'services.step1Desc'], ['02', 'services.step2Title', 'services.step2Desc'], ['03', 'services.step3Title', 'services.step3Desc'], ['04', 'services.step4Title', 'services.step4Desc']];
  return <main className="pt-20"><section className="relative py-28 bg-stone-900 overflow-hidden"><img src="https://images.pexels.com/photos/36770103/pexels-photo-36770103.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Modern museum" className="absolute inset-0 w-full h-full object-cover opacity-30" /><div className="absolute inset-0 bg-stone-950/70" /><div className="relative max-w-4xl mx-auto px-4 text-center"><p className="eyebrow text-amber-400">PickeyArt</p><h1 className="page-title">{t('services.title')}</h1><p className="page-subtitle">{t('services.subtitle')}</p></div></section><section className="py-24 bg-stone-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(([Icon, title, desc]) => <div key={title} className="group bg-white rounded-2xl p-7 border border-stone-100 hover:border-amber-200 hover:shadow-xl transition-all duration-300"><div className="w-12 h-12 rounded-xl bg-amber-50 text-amber-800 flex items-center justify-center mb-6 group-hover:bg-amber-800 group-hover:text-white transition-colors"><Icon className="w-6 h-6" /></div><h3 className="text-xl font-serif font-bold text-stone-800 mb-3">{t(title)}</h3><p className="text-sm text-stone-500 leading-relaxed">{t(desc)}</p></div>)}</div></div></section><section className="py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-14"><p className="eyebrow">PickeyArt</p><h2 className="section-title">{t('services.processTitle')}</h2><p className="section-subtitle mx-auto">{t('services.processSubtitle')}</p></div><div className="grid md:grid-cols-4 gap-8">{steps.map(([num, title, desc], index) => <div key={num} className="relative text-center">{index < 3 && <div className="hidden md:block absolute top-7 left-1/2 w-full border-t border-dashed border-amber-200" />}<div className="relative w-14 h-14 mx-auto rounded-full bg-amber-800 text-white flex items-center justify-center font-serif font-bold text-lg ring-8 ring-amber-50">{num}</div><h3 className="mt-6 text-lg font-serif font-bold text-stone-800">{t(title)}</h3><p className="mt-2 text-sm text-stone-500 leading-relaxed">{t(desc)}</p></div>)}</div><div className="mt-16 text-center"><button onClick={() => onNavigate('contact')} className="inline-flex items-center gap-3 px-6 py-3 rounded-full bg-amber-800 hover:bg-amber-900 text-white font-semibold transition-colors">{t('home.ctaButton')} <ArrowRight className="w-4 h-4" /></button></div></div></section></main>;
}
